[package]
name = "gambling"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "^0.8.4"
scottish_names = "^0.2.2"
titlecase = "1.0"